name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Instalar uv
        uses: astral-sh/setup-uv@v10
        with:
          version: "0.9.5"

      - name: Instalar dependencias
        run: uv sync --locked

      - name: Correr tests
        run: uv run pytest
